### PR TITLE
Make Travis post on Slack

### PR DESCRIPTION
**Pull request by hawkw**
I was getting tired of not having this. Travis will now post in #c0dez-b0tz

### CODE REVIEW

**Comment by carllerche** [comment]
IMO we should keep the updates going to a public destination.

**Comment by hawkw** [comment]
@carllerche I'm not entirely sure what you mean – I totally agree that Travis updates should be public, but currently it wasn't sending notifications anywhere? The commit status updates, status badge, and repository page on Travis' web UI should all remain public, and email updates should still be sent to anyone who's subscribed to them.

Should we consider creating a public Slack or Gitter channel for the repository & have Travis post to that as well? That might be its own issue...

**Comment by seanmonstar** [comment]
I can seek Carl's point. By it being in the public repo that it should notify a private Slack, it gives the impression of not being fully open.

Frankly I'd go even further and say we should move h2 (the lib) discussion out of Slack and to something public.

**Comment by carllerche** [comment]
We can either make a gitter for it or have some sort of `hyper-internals` or something on IRC.

**Comment by carllerche** [comment]
Closing for now. We can continue this discussion in a github issue if there is interest.

**Pull request closed without merging**
